import { fileURLToPath } from 'node:url';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { openDatabase } from './database.js';
import { createApp } from './app.js';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const db = openDatabase(process.env.GIS_DATABASE_PATH || path.join(root, 'server', 'visor.sqlite'));
const places = JSON.parse(readFileSync(path.join(root, 'server', 'places.json'), 'utf8'));
const app = createApp({ db, dataDirectory: path.join(root, 'public', 'data'), staticDirectory: path.join(root, 'dist'), places });
const port = Number(process.env.PORT || 3001);
const host = process.env.HOST || '127.0.0.1';
const server = app.listen(port, host, () => console.log(`API lista en http://${host}:${port}`));
const close = () => server.close(() => { db.close(); process.exit(0); });
process.on('SIGINT', close);
process.on('SIGTERM', close);
