import { useState } from 'react';
import { Alert, Button, Input, Select, Slider, Switch } from 'antd';
import type { RasterSource } from '../lib/raster.ts';
import { validateRaster, updateRaster } from '../lib/raster.ts';
import type { Bounds } from '../types.ts';

export function SourcesPanel({sources,onChange,fit,variant='layers'}:{sources:RasterSource[];onChange:(next:RasterSource[])=>void;fit:(bounds:Bounds)=>void;variant?:'layers'|'import'}) {
  const [role,setRole]=useState<'base'|'overlay'>('overlay');
  const [name,setName]=useState(''); const [url,setUrl]=useState(''); const [layers,setLayers]=useState(''); const [attribution,setAttribution]=useState(''); const [type,setType]=useState<'wms'|'wmts'>('wms'); const [error,setError]=useState('');
  const add=()=>{try{const next=validateRaster({id:`raster-${crypto.randomUUID()}`,name,type,url,layers,attribution,role,visible:true,opacity:1});onChange(updateRaster([...sources,next],next.id,{}));setError('');setUrl('');setName('');}catch(e){setError(String(e instanceof Error?e.message:e));}};
  const layerSources=sources.filter(source=>source.id!=='pnoa');
  return <section className="sources-panel" aria-label={variant==='layers'?'Capas de referencia':'Importar servicios de imágenes'}>{variant==='layers'?<>
    <div className="section-title"><span>CAPAS DE REFERENCIA</span><span>{layerSources.length}</span></div><p className="muted">Imágenes WMS y WMTS. La hidrografía oficial cubre España. Estas imágenes no añaden entidades al análisis.</p>
    {layerSources.map(source=><article className="source-card" key={source.id}><div className="source-title"><strong>{source.name}</strong><Switch checked={source.visible} aria-label={`Mostrar ${source.name}`} onChange={visible=>onChange(updateRaster(sources,source.id,{visible}))}/></div><p className="muted">{source.type.toUpperCase()} · {source.attribution}</p>{source.id!=='hydro'&&<label>Uso<Select aria-label={`Uso de ${source.name}`} value={source.role??'overlay'} options={[{value:'base',label:'Mapa base regional'},{value:'overlay',label:'Capa superpuesta'}]} onChange={role=>onChange(updateRaster(sources,source.id,{role}))}/></label>}<label>Opacidad {Math.round(source.opacity*100)}%<Slider ariaLabelForHandle={`Opacidad ${source.name}`} value={source.opacity} min={0} max={1} step={0.05} onChange={opacity=>onChange(sources.map(s=>s.id===source.id?{...s,opacity}:s))}/></label><div className="actions">{source.bounds&&<Button onClick={()=>fit(source.bounds!)}>Encuadrar</Button>}{source.id.startsWith('raster-')&&<Button onClick={()=>onChange(sources.filter(s=>s.id!==source.id))}>Quitar servicio</Button>}</div><a href={source.type==='wms'?`${source.url.split('?')[0]}?SERVICE=WMS&REQUEST=GetCapabilities`:source.url} target="_blank" rel="noreferrer">Descripción del servicio</a></article>)}
    <p className="muted">Elige PNOA en «Mapa y relieve». Añade otros servicios en «Importar».</p>
  </>:<>
    <h2>Importar WMS o WMTS</h2><p>Son servicios de imágenes. Consulta GetCapabilities para conocer sus capas y atribución. Los servicios registrados aparecen en «Capas».</p><details><summary>Registrar servicio de imágenes</summary><p>WMS 1.1.1 EPSG:3857; WMTS solo matrices Web Mercator equivalentes a XYZ. Una página con un visor no es un servicio importable.</p><div className="form-stack"><Select aria-label="Uso del nuevo servicio" value={role} options={[{value:'base',label:'Mapa base regional'},{value:'overlay',label:'Capa superpuesta'}]} onChange={setRole}/><Select aria-label="Tipo de servicio" value={type} options={[{value:'wms',label:'WMS'},{value:'wmts',label:'WMTS compatible XYZ'}]} onChange={setType}/><Input aria-label="Nombre del servicio" placeholder="Nombre" value={name} onChange={e=>setName(e.target.value)}/><Input aria-label="URL del servicio" placeholder="https://…" value={url} onChange={e=>setUrl(e.target.value)}/>{type==='wms'&&<Input aria-label="Capas WMS" placeholder="Nombre técnico de la capa" value={layers} onChange={e=>setLayers(e.target.value)}/>}<Input aria-label="Atribución del servicio" placeholder="Proveedor y atribución" value={attribution} onChange={e=>setAttribution(e.target.value)}/><Button onClick={add}>Registrar servicio</Button>{error&&<Alert type="error" message={error}/>}</div></details><p className="muted">Un mapa base regional cubre el fondo solo donde aporta imagen. El fondo general sigue visible fuera de su cobertura.</p>
  </>}
  </section>;
}
