import { useState } from 'react';
import { Alert, Button, Input, Select, Slider, Switch } from 'antd';
import type { RasterSource } from '../lib/raster.ts';
import { validateRaster } from '../lib/raster.ts';
import type { Bounds } from '../types.ts';

export function SourcesPanel({sources,onChange,fit}:{sources:RasterSource[];onChange:(next:RasterSource[])=>void;fit:(bounds:Bounds)=>void}) {
  const [name,setName]=useState(''); const [url,setUrl]=useState(''); const [layers,setLayers]=useState(''); const [attribution,setAttribution]=useState(''); const [type,setType]=useState<'wms'|'wmts'>('wms'); const [error,setError]=useState('');
  const add=()=>{try{const next=validateRaster({id:`raster-${crypto.randomUUID()}`,name,type,url,layers,attribution,visible:true,opacity:0.8});onChange([...sources,next]);setError('');setUrl('');setName('');}catch(e){setError(String(e instanceof Error?e.message:e));}};
  return <section className="sources-panel"><h2>Fuentes oficiales y servicios</h2><p>Imágenes de referencia. No contienen entidades vectoriales para el análisis. Los dos ejemplos oficiales cubren España.</p>
    {sources.map(source=><article className="source-card" key={source.id}><div className="source-title"><strong>{source.name}</strong><Switch checked={source.visible} aria-label={`Mostrar ${source.name}`} onChange={visible=>onChange(sources.map(s=>s.id===source.id?{...s,visible}:s))}/></div><p className="muted">{source.type.toUpperCase()} · {source.attribution}</p><label>Opacidad {Math.round(source.opacity*100)}%<Slider ariaLabelForHandle={`Opacidad ${source.name}`} value={source.opacity} min={0} max={1} step={0.05} onChange={opacity=>onChange(sources.map(s=>s.id===source.id?{...s,opacity}:s))}/></label><div className="actions">{source.bounds&&<Button onClick={()=>fit(source.bounds!)}>Ver España</Button>}{source.id.startsWith('raster-')&&<Button onClick={()=>onChange(sources.filter(s=>s.id!==source.id))}>Quitar servicio</Button>}</div><a href={source.type==='wms'?`${source.url.split('?')[0]}?SERVICE=WMS&REQUEST=GetCapabilities`:source.url} target="_blank" rel="noreferrer">Descripción del servicio</a></article>)}
    <details><summary>Añadir WMS o WMTS</summary><p>Consulta GetCapabilities para conocer capas, proyecciones y atribución. WMS 1.1.1 EPSG:3857; WMTS solo matrices Web Mercator equivalentes a XYZ. No se importa una página de otro visor.</p><div className="form-stack"><Select aria-label="Tipo de servicio" value={type} options={[{value:'wms',label:'WMS'},{value:'wmts',label:'WMTS compatible XYZ'}]} onChange={setType}/><Input aria-label="Nombre del servicio" placeholder="Nombre" value={name} onChange={e=>setName(e.target.value)}/><Input aria-label="URL del servicio" placeholder="https://…" value={url} onChange={e=>setUrl(e.target.value)}/>{type==='wms'&&<Input aria-label="Capas WMS" placeholder="Nombre técnico de la capa" value={layers} onChange={e=>setLayers(e.target.value)}/>}<Input aria-label="Atribución del servicio" placeholder="Proveedor y atribución" value={attribution} onChange={e=>setAttribution(e.target.value)}/><Button onClick={add}>Registrar servicio</Button>{error&&<Alert type="error" message={error}/>}</div></details>
  </section>;
}
